UnivarsityManagemantSystem/Models/CourseAssign.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UnivarsityManagemantSystem.Models
{
    public class CourseAssign
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int TeacherId { get; set; }   
        public int CourseId { get; set; }
     
    }
}

UnivarsityManagemantSystem/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnivarsityManagemantSystem.Models;
using UnivarsityManagemantSystem.Gateway;
using UnivarsityManagemantSystem.BLL;

namespace UnivarsityManagemantSystem.Controllers
{
    public class CourseAssignController : Controller
    {
        CourseAssignManager aCourseAssignManager = new CourseAssignManager();
        CourseManager aCourseManager = new CourseManager();
        DepartmentManager aDepartmentManager = new DepartmentManager();
        TeacherManager aTeacherManager = new TeacherManager();

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Departments = aDepartmentManager.GetAllDepartment();
            ViewBag.Teachers = aTeacherManager.GetAllTeacher();
            ViewBag.Courses = aCourseManager.GetAllCourse();
            return View();
        }
        [HttpPost]
        public ActionResult Create(CourseAssign courseAssign )
        {
           
            ViewBag.Departments = aDepartmentManager.GetAllDepartment();
            ViewBag.Teachers = aTeacherManager.GetAllTeacher();
            ViewBag.Courses = aCourseManager.GetAllCourse();
            ViewBag.Message = aCourseAssignManager.Save(courseAssign);
            return View();
        }
        public JsonResult GetTeacherByDepartmentId(Department department)
        {
            var teachers = aTeacherManager.GetAllTeacher();
            var teacherList = teachers.Where(t =>t.DepartmentId == department.DeptId).ToList();
            return Json(teacherList);
        }
        public JsonResult GetTeacherById(int teacherId)
        {
            List<Teacher> teachers =aTeacherManager.GetAllTeacher();
            Teacher aTeacher = teachers.ToList().Find(t => t.TeacherId == teacherId);
            return Json(aTeacher);

        }
        public JsonResult GetCourseById(int courseId)
        {
            List<Course> courses = aCourseManager.GetAllCourse();
            Course aCourse = courses.ToList().Find(c => c.CourseId == courseId);
            return Json(aCourse);
        }
        public ActionResult Index()
        {
            return View();
        }
	}
}

UnivarsityManagemantSystem/Views/CourseAssign/Create.cshtml
@using UnivarsityManagemantSystem.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_FacultyLayout.cshtml";
    List<Department> departments = ViewBag.Departments;
    //List<Teacher> teachers = ViewBag.Teachers;
    List<Course> courses = ViewBag.Courses;
}


<h4><i class="icon-plus-sign">Assign Course</i></h4>
<!DOCTYPE html>
@section style
    {
    <style>
        label.error {
            color: red;
            font-style: italic;
            display: inline;
        }
    </style>
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    
</head>
<body>
    <div>
        <form method="POST" id="saveAssignCourseForm">
            <table>
               
              

                <tr>
                    <td><label for="DepartmentId">Department : </label></td>
                    <td>
                        <select id="DepartmentId" name="DepartmentId">
                            <option value="">- - - - - - - - - Select - - - - - - - - -</option>
                            @foreach (Department department in departments)
                            {
                                <option value="@department.DeptId">@department.DeptName</option>

                            }
                        </select>

                    </td>

                </tr>

                <tr>
                    <td><label for="TeacherId">Teacher: </label></td>
                    <td>
                        <select id="TeacherId" name="TeacherId">
                            @*<option value="">- - - Select - - -</option>*@

                        </select>
                    </td>
                </tr>

                <tr>
                    <td><label for="CraditTaken">Credit To Be Taken : </label></td>
                    <td>
                      
                        <input type="text" id="CraditTaken" name="CraditTaken" readonly="readonly"/>
                    </td>
                </tr>
                @*<tr>
                    <td><label for="RemainingCradit">Remaing Credit : </label></td>
                    <td>
                        <input type="text" id="RemainingCradit" name="RemainingCradit" readonly="readonly" />
                    </td>
                </tr>*@
                <tr>
                  
                    <td><label for="CourseId">Course Code : </label></td>
                    <td>
                        <select id="CourseId" name="CourseId">
                            <option value="">- - - - - - - - - Select - - - - - - - - -</option>
                            @foreach (Course course in courses)
                            {
                                <option value="@course.CourseId">@course.CourseCode</option>

                            }
                        </select>

                    </td>

                </tr>

                <tr>
                    <td><label for="CourseName">Name : </label></td>
                    <td>

                        <input type="text" id="CourseName" name="CourseName" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td><label for="Cradit">Credit : </label></td>
                    <td>

                        <input type="text" id="Cradit" name="Cradit" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" class="btn btn-success" value="Assign" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td><h4>@ViewBag.Message</h4></td>
                </tr>
            </table>
        </form>
    </div>
    @section scripts{
        <script src="~/Scripts/jquery-1.10.2.js"></script>
         <script src="~/Scripts/jquery-3.3.1.js"></script>
    
        <script src="~/Scripts/jquery.validate.js"></script>
    

        <script>
            $("#saveAssignCourseForm").validate({
                rules: {
                    DepartmentId: "required",
                    TeacherId: "required",                 
                    CourseId: "required",
                   
                },
                messages: {
                    DepartmentId: "Please select a department",
                    TeacherId: "Please select a teacher",
                    CourseId: "Please select a course",
                  
                }
            });

            $(document).ready(function () {
                $("#DepartmentId").change(function () {
                    var deptId = $("#DepartmentId").val();                 
                    $("#TeacherId").empty();                   
                    $("#TeacherId").append('<option value=' + "" + '>- - - - - - Select Teacher - - - - - - </option>');                   
                    var json = { DeptId: deptId };                
                    $.ajax({
                        type: "POST",
                         url: '@Url.Action("GetTeacherByDepartmentId", "CourseAssign")',
                        //url: '/CourseAssign/GetTeacherByDepartmentId',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (teachers) {

                            $.each(teachers, function (key, value) {
                              
                                $("#TeacherId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                             
                            });

                        }
                    });
                   
                });

               
                //------Show Teacher Information--------
                $("#TeacherId").change(function () {
                    var id = $("#TeacherId").val();
                    var json = { teacherId: id };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetTeacherById","CourseAssign")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            var craditToBeTaken = data.CraditTaken;
                           
                            $("#CraditTaken").val(craditToBeTaken);
                           
                        }
                    });
                });
                //------Show Course Information--------
                $("#CourseId").change(function () {
                    var id = $("#CourseId").val();
                    var json = { courseId: id };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCourseById", "CourseAssign")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            var courseName = data.CourseName;
                            var cradit = data.Cradit;

                            $("#CourseName").val(courseName);
                            $("#Cradit").val(cradit);
                        }
                    });
                });

            });

        </script>
    }
</body>
</html>