UnivarsityManagemantSystem/Models/StudentResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UnivarsityManagemantSystem.Models
{
    public class StudentResult
    {
        public int ResultId { get; set; } 
        public int StudentId { get; set; }
        public string RegNo { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string DepartmentName { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string GradeId { get; set; } 
    }
}

UnivarsityManagemantSystem/Controllers/StudentResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnivarsityManagemantSystem.Models;
using UnivarsityManagemantSystem.Gateway;
using UnivarsityManagemantSystem.BLL;

namespace UnivarsityManagemantSystem.Controllers
{
    public class StudentResultController : Controller
    {
        StudentManager aStudentManager = new StudentManager();
        CourseManager aCourseManager = new CourseManager();
        StudentResultManager aStudentResultManager = new StudentResultManager();
        GradeManager aGradeManager = new GradeManager();
        [HttpGet]
        public ActionResult SaveResult()
        {
            ViewBag.GradeList = aGradeManager.getAllGrades();
            ViewBag.StudentList = aStudentManager.GetAllStudent();
            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(StudentResult studentResult , int studentId)  
        {
            ViewBag.GradeList = aGradeManager.getAllGrades();
            ViewBag.StudentList = aStudentManager.GetAllStudent();
            ViewBag.Message = aStudentResultManager.Save(studentResult);
            return View();
        }
        public JsonResult GetStudentById(int studentId)
        {

            List<StudentResult> students = aStudentResultManager.getResult(studentId);
            StudentResult aStudent = students.ToList().Find(e => e.StudentId == studentId);
            return Json(aStudent);
        }
        public JsonResult GetCourseById(Student student)
        {
            var courses = aCourseManager.GetAllCourse();
            var courseList = courses.Where(c => c.DepartmentId == student.DepartmentId).ToList();
            return Json(courses);
        }
	}
}

UnivarsityManagemantSystem/Views/StudentResult/SaveResult.cshtml
@using UnivarsityManagemantSystem.Models
@{
    ViewBag.Title = "SaveResult";
    Layout = "~/Views/Shared/_FacultyLayout.cshtml";
    List<Course> courses = ViewBag.CourseList;
    List<Student> students = ViewBag.StudentList;
    List<Grade> grades = ViewBag.GradeList;
}

<h4><i class="icon-plus-sign">Save Result</i></h4>
<!DOCTYPE html>
@section style
    {
    <style>
        label.error {
            color: red;
            font-style: italic;
            display: inline;
        }
    </style>

}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    
</head>
<body>
    <div>
        <form method="POST" id="saveSaveResultForm">
            <table>



                <tr>
                    <td><label for="StudentId">Student Reg No : </label></td>
                    <td>
                        <select id="StudentId" name="StudentId">
                            <option value="">- - - - - - - - - Select - - - - - - - - -</option>
                            @foreach (Student student in students)
                            {
                                <option value="@student.StudentId">@student.RegNo</option>

                            }
                        </select>

                    </td>

                </tr>
                <tr>
                    <td><label for="StudentName">Name : </label></td>
                    <td>

                        <input type="text" id="StudentName" name="StudentName" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td><label for="Email">Email : </label></td>
                    <td>

                        <input type="text" id="Email" name="Email" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td><label for="DepartmentName">Department : </label></td>
                    <td>

                        <input type="text" id="DepartmentName" name="DepartmentName" readonly="readonly" />
                    </td>
                </tr>


                <tr>
                    <td><label for="CourseId">Course : </label></td>
                    <td>
                        <select id="CourseId" name="CourseId">
                            <option value="">- - - - - - - - - Select - - - - - - - - -</option>

                        </select>
                    </td>
                </tr>
               
                <tr>
                    <td><label for="">Grade Letter : </label></td>
                    <td>
                        <select id="GradeId" name="GradeId">
                            <option value="">- - - - - - - - - Select - - - - - - - - -</option>
                            @foreach(Grade grade in grades)
                            {
                                <option value="@grade.GradeId">@grade.GradeLetter</option>
                            }
                        </select>
                       
                    </td>
                </tr>


                <tr>
                    <td></td>
                    <td><input type="submit" class="btn btn-success" value="Save" /></td>

                </tr>
                <tr>
                    <td></td>
                    <td><h4>@ViewBag.Message</h4></td>
                </tr>
            </table>
        </form>
    </div>
    @section scripts{
        <script src="~/Scripts/jquery-1.10.2.js"></script>
        <script src="~/Scripts/jquery-3.3.1.js"></script>

        <script src="~/Scripts/jquery.validate.js"></script>


        <script>
            $("#saveSaveResultForm").validate({
                rules: {
                    StudentId: "required",
                    CourseId: "required",
                    GradeId: "required"
                },
                messages: {
                    StudentId: "Please select registration number",
                    CourseId: "Please select a course",
                    GradeId: "Please select a grade"
                }
            });

            $(document).ready(function () {
                $("#StudentId").change(function () {
                    var id = $("#StudentId").val();
                  
                    var json = { StudentId: id};

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetStudentById","StudentResult")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            var studentName = data.StudentName;
                            var email = data.Email;
                            var departmentName = data.DepartmentName
                            $("#StudentName").val(studentName);
                            $("#Email").val(email);
                            $("#DepartmentName").val(departmentName);

                        }
                    });
                });

                //show course
                $("#StudentId").change(function () {
                    var id = $("#StudentId").val();
                    $("#CourseId").empty();
                    $("#CourseId").append('<option value=' + "" + '>- - - - - - Select Course - - - - - - </option>');
                    var json = { StudentId: id };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCourseById", "EnrollCourse")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (courses) {

                            $.each(courses, function (key, value) {

                                $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseName + '</option>');

                            });

                        }
                    });
                });

            });

        </script>
    }
</body>
</html>